dictionaryDefinitions:
 - name: sauronDictionary
   path: ./cSpell.txt
   addWords: true
dictionaries:
 - sauronDictionary
ignorePaths:
 - 'cspell.config.yml'
 - 'cSpell.txt'
 - 'node_modules'
 - 'package.json'
 - 'commitlint.config.js'
 - 'lefthook.yml'
 - 'biome.json'
 - 'bun.lockb'
